TEMPLATE = subdirs

SUBDIRS += \
    tst_cellfocusdelegate \
    tst_tpmcalculator \
    tst_xmlbuilder \
    tst_zipwriter \
    tst_excelreader \
    tst_sheetprocessors \
    tst_dataprocessor \
    tst_plotengine \
    tst_pptxwriter \
    tst_imageutils \
    tst_reportgenerator \
    tst_sopLoader \
    tst_reportlayout \
    tst_responsivelayout \
    tst_slidecanvasitems \
    tst_layoutcommand \
    tst_identitymanager \
    tst_configloader \
    tst_compatclassifier \
    tst_postgresconnection \
    tst_notificationlistener \
    tst_livesync \
    tst_presencemanager \
    tst_migrationtool \
    tst_databasemanager \
    tst_writeoutcome \
    tst_offlinesnapshot \
    tst_connectionmonitor \
    tst_offlinebanner \
    tst_planc_checkpoint \
    tst_sensoryreportsource \
    tst_twoclient_e2e \
    tst_presencedotsdelegate \
    tst_sensorydataplaceholder \
    tst_storedfns \
    tst_versionlookup \
    tst_mainwindow_remotecell \
    tst_apptheme \
    tst_regimeutils \
    tst_testerround \
    tst_outputpaths \
    tst_rawgridjson \
    tst_reportdatajson \
    tst_detailedsensoryjson \
    tst_recoverymanager \
    tst_recoverdialog \
    tst_excelwritepayload \
    tst_saveintegrity_e2e
