#pragma once
#include <QStringList>

namespace DVE { namespace testutil {

// Workbooks for the v3 harnesses: the in-repo synthetic fixtures
// (tests/data/*.xlsx, generated by tests/generate_fixtures.py) plus every
// .xlsx under $DVE_TEST_CORPUS_DIR (recursive) when that env var is set.
// An unset/missing corpus dir is NOT an error - harnesses run on fixtures
// alone (same skip-clean philosophy as DVE_TEST_PG_CONN).
QStringList corpusFiles();
QString     corpusDirDescription();   // "fixtures only" or the corpus dir path

}} // namespace DVE::testutil
