# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['translator_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('translate_excel.py',      '.'),
        ('translate_powerpoint.py', '.'),
        ('translate_image.py',      '.'),
        ('resources/ccell_icon.ico', 'resources'),
    ],
    hiddenimports=[
        'translate_excel',
        'translate_powerpoint',
        'translate_image',
        'pptx',
        'pptx.util',
        'pptx.oxml',
        'pptx.opc',
        'openpyxl',
        'openpyxl.chart',
        'openpyxl.chart.text',
        'openpyxl.drawing.text',
        'anthropic',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'fitz',
        'pymupdf',
        'lxml',
        'lxml.etree',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'sqlalchemy',
        'pandas',
        'scipy',
        'matplotlib',
        'numpy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DocumentTranslator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/ccell_icon.ico',
)
